version: '3.9'

services:

  webserver:
    image: nginx:1.25
    env_file:
      - webserver.env
    depends_on:
      web:
        condition: service_started
    volumes:
      - ./docker_volumes/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./docker_volumes/webserver/templates:/etc/nginx/templates
    restart: always
    ports:
      - "2222:2222"

  db:
    image: mysql:8.0
    env_file:
      - db.env
    volumes:
      - ./docker_volumes/db:/var/lib/mysql
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    ports:
      - "13306:3306"

  redis:
    image: redis:6.0
    restart: always
    ports:
      - "16379:6379"

  api_http:
    image: greenchatapi_http
    env_file:
      - api.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      api_http_email:
        condition: service_started
    volumes:
      - ./api/media:/api/media
    restart: always
    ports:
      - "5181:5181"

  api_http_email:
    image: greenchatapi_http_email
    env_file:
      - api.env
    restart: always

  api_websocket:
    image: greenchatapi_websocket
    env_file:
      - api.env
    restart: always
    ports:
      - "5180:5180"

  web:
    image: greenchatweb
    env_file:
      - web.env
    depends_on:
      api_http:
        condition: service_started
      api_http_email:
        condition: service_started
      api_websocket:
        condition: service_started
    restart: always
    ports:
      - "5182:5182"
