FROM python:3.11

COPY ./api /api
COPY ./requirements.txt /api/requirements.txt
WORKDIR /api

RUN apt update
RUN pip3 install -r requirements.txt

ENV PYTHONPATH=/

CMD ["python3", "websocket_/main.py"]
